# Generated by Django 4.0.5 on 2022-09-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.EmailField(max_length=250, verbose_name='Email:')),
                ('category', models.CharField(max_length=250, verbose_name='Category:')),
            ],
        ),
    ]
